SKILL_TAXONOMY: tuple[str, ...] = (
    "python",
    "typescript",
    "javascript",
    "java",
    "c++",
    "c#",
    "go",
    "rust",
    "scala",
    "kotlin",
    "react",
    "next.js",
    "node.js",
    "fastapi",
    "django",
    "flask",
    "spring",
    "sql",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "graphql",
    "rest api",
    "microservices",
    "system design",
    "distributed systems",
    "docker",
    "kubernetes",
    "aws",
    "gcp",
    "azure",
    "terraform",
    "ci/cd",
    "github actions",
    "linux",
    "data structures",
    "algorithms",
    "machine learning",
    "deep learning",
    "nlp",
    "llm",
    "openai",
    "prompt engineering",
    "rag",
    "vector database",
    "pandas",
    "numpy",
    "spark",
    "hadoop",
    "airflow",
    "etl",
    "analytics",
    "product sense",
    "leadership",
    "mentoring",
    "communication",
    "experimentation",
    "a/b testing",
    "figma",
    "tailwind",
    "html",
    "css",
    "chrome extension",
)
